# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181007_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Posts', unique=True)),
            ],
        ),
    ]
